spring:

  datasource:
      url: jdbc:mariadb://maria:3306/template?createDatabaseIfNotExist=true
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false

server:
  context-path: /template
  port: 8080

security:
  basic:
    enabled: false

management:
  security.enabled: false

logging:
  file: logs/template.log
  level:
    root: info
    com.company.template: info

flyway:
  enabled: true

levelog:
  kafka:
    enabled: true

template.kafka.brokers: kafka:9092