spring:

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: false

server:
  servlet:
    context-path: /template
  port: 8080

security:
  basic.enabled: false

management:
  security.enabled: false

logging:
  level:
    root: info
    com.company.template: debug

levelog:
  rest:
    enabled: true