spring:

  flyway:
    enabled: true

  datasource:
      url: jdbc:mariadb://maria:3306/template?createDatabaseIfNotExist=true
      username: root
      password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /template

logging:
  file: logs/template.log
  level:
    root: info
    com.company.template: info

levelog:
  kafka:
    enabled: true

template.kafka.brokers: kafka:9092